version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test-and-deploy:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python test.py
  build-and-test:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: echo Hello
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: echo helo
      - sonarcloud/scan

workflows:
  sample: 
    jobs:
      - build:
          context:  SonarCloud
      - build-and-test-and-deploy
